version: '3.8'

services:
  foodapp_backend:
    image: 352311919031.dkr.ecr.us-east-1.amazonaws.com/swarmtaskfbackend:latest
    expose:
      - "4000"
    networks:
      - appnet
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:4000/health || exit 1"]
      interval: 30s
      retries: 3
      timeout: 10s

  foodapp_frontend:
    image: 352311919031.dkr.ecr.us-east-1.amazonaws.com/swarmtaskfrontend:latest
    expose:
      - "80"
    networks:
      - appnet
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  foodapp_nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    configs:
      - source: nginx_conf
        target: /etc/nginx/conf.d/default.conf
    networks:
      - appnet
    deploy:
      replicas: 1
      restart_policy:
        condition: any

networks:
  appnet:
    driver: overlay
    attachable: true

configs:
  nginx_conf:
    file: ./nginx.conf