version: "3.8"

services:

  foodapp_backend:
    image: 352311919031.dkr.ecr.us-east-1.amazonaws.com/swarmtaskfbackend:${IMAGE_TAG:-latest}
    networks:
      - appnet
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
        failure_action: rollback
        monitor: 30s
      rollback_config:
        parallelism: 1
        delay: 5s
        order: start-first
        failure_action: pause
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  foodapp_frontend:
    image: 352311919031.dkr.ecr.us-east-1.amazonaws.com/swarmtaskfrontend:${IMAGE_TAG:-latest}
    ports:
      - "80:80"   # 👈 IMPORTANT (expose nginx)
    networks:
      - appnet
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
        failure_action: rollback
        monitor: 20s
      rollback_config:
        parallelism: 1
        delay: 5s
        order: start-first
        failure_action: pause
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

networks:
  appnet:
    driver: overlay
    attachable: true