name: Manual Rollback - Swarm (TL Control)

on:
  workflow_dispatch:

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:

    - name: Configure AWS OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/myoidcrole
        aws-region: us-east-1

    - name: Execute Rollback
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}

        script: |
          STACK="foodapp"

          echo "ROLLBACK STARTED"

          # 🔥 Read previous version file
          cat /tmp/prev_version.txt

          BACKEND_IMAGE=$(grep backend /tmp/prev_version.txt | awk '{print $2}')
          FRONTEND_IMAGE=$(grep frontend /tmp/prev_version.txt | awk '{print $2}')

          echo "Rolling back to previous version..."

          docker service update --image $BACKEND_IMAGE ${STACK}_foodapp_backend
          docker service update --image $FRONTEND_IMAGE ${STACK}_foodapp_frontend

          echo "ROLLBACK DONE"
          docker service ls